/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiPublicHooksPushDigestRouteImport } from './routes/api/public/hooks/push-digest'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPushDigestRoute =
  ApiPublicHooksPushDigestRouteImport.update({
    id: '/api/public/hooks/push-digest',
    path: '/api/public/hooks/push-digest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/api/public/hooks/push-digest': typeof ApiPublicHooksPushDigestRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/api/public/hooks/push-digest': typeof ApiPublicHooksPushDigestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/api/public/hooks/push-digest': typeof ApiPublicHooksPushDigestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/app' | '/auth' | '/api/public/hooks/push-digest'
  fileRoutesByTo: FileRoutesByTo
  to: '/app' | '/auth' | '/api/public/hooks/push-digest'
  id: '__root__' | '/app' | '/auth' | '/api/public/hooks/push-digest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  ApiPublicHooksPushDigestRoute: typeof ApiPublicHooksPushDigestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/push-digest': {
      id: '/api/public/hooks/push-digest'
      path: '/api/public/hooks/push-digest'
      fullPath: '/api/public/hooks/push-digest'
      preLoaderRoute: typeof ApiPublicHooksPushDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  ApiPublicHooksPushDigestRoute: ApiPublicHooksPushDigestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
